"""
Default settings and voice presets for Alastor TTS and DSP.
"""

DEFAULT_SETTINGS = {
    "voice": "ru-RU-DmitryNeural",
    "rate": "+8%",
    "pitch": "+2Hz",
    "enabled": True,
    "dsp_enabled": True,
    "filter_profile": "canon_radio",
    "demon_layer": True,
    "add_vinyl": True,
    "vinyl_intensity": 1.0,
    "highpass_hz": 350.0,
    "lowpass_hz": 3800.0,
    "drive_db": 6.0
}

VOICE_PRESETS = {
    "alastor_canon": {
        "title": "📻 Каноничный Аластор (Отель Хазбин)",
        "voice": "ru-RU-DmitryNeural",
        "rate": "+8%",
        "pitch": "+2Hz",
        "filter_profile": "canon_radio",
        "demon_layer": True,
        "dsp_enabled": True,
        "add_vinyl": True,
        "vinyl_intensity": 1.0,
        "highpass_hz": 350.0,
        "lowpass_hz": 3800.0,
        "drive_db": 6.0
    },
    "vintage_gramophone": {
        "title": "📻 Старый патефон / Граммофон 1920-х",
        "voice": "ru-RU-DmitryNeural",
        "rate": "+12%",
        "pitch": "+4Hz",
        "filter_profile": "gramophone",
        "demon_layer": True,
        "dsp_enabled": True,
        "add_vinyl": True,
        "vinyl_intensity": 2.2,
        "highpass_hz": 480.0,
        "lowpass_hz": 2600.0,
        "drive_db": 10.0
    },
    "am_radio": {
        "title": "📻 Коротковолновый эфир (Шумный AM)",
        "voice": "ru-RU-DmitryNeural",
        "rate": "+8%",
        "pitch": "+2Hz",
        "filter_profile": "am_radio",
        "demon_layer": True,
        "dsp_enabled": True,
        "add_vinyl": True,
        "vinyl_intensity": 1.6,
        "highpass_hz": 420.0,
        "lowpass_hz": 3100.0,
        "drive_db": 8.0
    },
    "walkie_talkie": {
        "title": "📻 Армейская рация / Walkie-Talkie",
        "voice": "en-US-AndrewMultilingualNeural",
        "rate": "+10%",
        "pitch": "+0Hz",
        "filter_profile": "walkie_talkie",
        "demon_layer": False,
        "dsp_enabled": True,
        "add_vinyl": False,
        "vinyl_intensity": 0.0,
        "highpass_hz": 500.0,
        "lowpass_hz": 3000.0,
        "drive_db": 10.0
    },
    "vintage_phone": {
        "title": "📞 Телефонная трубка (1960-е)",
        "voice": "ru-RU-DmitryNeural",
        "rate": "+4%",
        "pitch": "+0Hz",
        "filter_profile": "telephone",
        "demon_layer": False,
        "dsp_enabled": True,
        "add_vinyl": False,
        "vinyl_intensity": 0.0,
        "highpass_hz": 400.0,
        "lowpass_hz": 2800.0,
        "drive_db": 4.0
    },
    "street_megaphone": {
        "title": "📢 Уличный рупор / Мегафон",
        "voice": "en-US-AndrewMultilingualNeural",
        "rate": "+14%",
        "pitch": "+3Hz",
        "filter_profile": "megaphone",
        "demon_layer": False,
        "dsp_enabled": True,
        "add_vinyl": False,
        "vinyl_intensity": 0.0,
        "highpass_hz": 600.0,
        "lowpass_hz": 3500.0,
        "drive_db": 14.0
    },
    "demon_overlord": {
        "title": "😈 Демонический Владыка (Темный бас)",
        "voice": "ru-RU-DmitryNeural",
        "rate": "-4%",
        "pitch": "-12Hz",
        "filter_profile": "demon_radio",
        "demon_layer": True,
        "dsp_enabled": True,
        "add_vinyl": True,
        "vinyl_intensity": 0.8,
        "highpass_hz": 180.0,
        "lowpass_hz": 4500.0,
        "drive_db": 12.0
    },
    "shadow_echo": {
        "title": "🏛️ Театр теней (Призрачное эхо)",
        "voice": "de-DE-FlorianMultilingualNeural",
        "rate": "-2%",
        "pitch": "-4Hz",
        "filter_profile": "shadow_realm",
        "demon_layer": True,
        "dsp_enabled": True,
        "add_vinyl": True,
        "vinyl_intensity": 0.5,
        "highpass_hz": 250.0,
        "lowpass_hz": 5200.0,
        "drive_db": 5.0
    },
    "studio_podcast": {
        "title": "🎙️ Студийный подкаст (Тёплый бас без шумов)",
        "voice": "en-US-BrianMultilingualNeural",
        "rate": "+0%",
        "pitch": "+0Hz",
        "filter_profile": "studio_warm",
        "demon_layer": False,
        "dsp_enabled": True,
        "add_vinyl": False,
        "vinyl_intensity": 0.0,
        "highpass_hz": 80.0,
        "lowpass_hz": 12000.0,
        "drive_db": 0.0
    },
    "studio_crystal": {
        "title": "🎙️ Кристальная студия (High-End)",
        "voice": "ru-RU-DmitryNeural",
        "rate": "+0%",
        "pitch": "+0Hz",
        "filter_profile": "studio_crystal",
        "demon_layer": False,
        "dsp_enabled": True,
        "add_vinyl": False,
        "vinyl_intensity": 0.0,
        "highpass_hz": 60.0,
        "lowpass_hz": 16000.0,
        "drive_db": 0.0
    },
    "studio_latenight": {
        "title": "🎙️ Ночной радиоведущий (Глубокий бархат)",
        "voice": "fr-FR-RemyMultilingualNeural",
        "rate": "-3%",
        "pitch": "-6Hz",
        "filter_profile": "studio_latenight",
        "demon_layer": False,
        "dsp_enabled": True,
        "add_vinyl": False,
        "vinyl_intensity": 0.0,
        "highpass_hz": 70.0,
        "lowpass_hz": 11000.0,
        "drive_db": 0.0
    },
    "clean_voice": {
        "title": "🎙️ Чистый диктор (Bypass / Без эффектов)",
        "voice": "ru-RU-DmitryNeural",
        "rate": "+0%",
        "pitch": "+0Hz",
        "filter_profile": "clean",
        "demon_layer": False,
        "dsp_enabled": False,
        "add_vinyl": False,
        "vinyl_intensity": 0.0,
        "highpass_hz": 50.0,
        "lowpass_hz": 18000.0,
        "drive_db": 0.0
    },
    "english_alastor": {
        "title": "🇺🇸 Alastor (English Broadcast)",
        "voice": "en-US-GuyNeural",
        "rate": "+6%",
        "pitch": "+2Hz",
        "filter_profile": "canon_radio",
        "demon_layer": True,
        "dsp_enabled": True,
        "add_vinyl": True,
        "vinyl_intensity": 1.0,
        "highpass_hz": 350.0,
        "lowpass_hz": 3800.0,
        "drive_db": 6.0
    }
}
